name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          profile: minimal

      - name: Install dependencies
        run: cargo fetch

      - name: Build and Test
        run: cargo build --verbose && cargo test --verbose
